name: flutter_teste_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter: ^0.11.0

  cupertino_icons: ^1.0.2
  pie_chart: ^5.1.0
  lottie: ^1.3.0
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.5
  date_time_picker: ^2.1.0
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.0.3
  scaffold_gradient_background: ^1.0.3+1
  intl: ^0.17.0
  pdf: ^3.8.2
  printing: ^5.9.2
  shared_preferences: ^2.0.15
  flutter_signin_button: ^2.0.0  
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
